#ifndef GAME_OF_LIFE_CONSTANTS_H

//GRID DIMMENSIONS
#define GRID_WIDTH 50
#define GRID_HEIGHT 50
//WINDOW DIMMENSIONS
#define WINDOW_WIDTH 500
#define WINDOW_HEIGHT 500
//DISPLAY REFRESH TIME DELTA (ms)
#define DELTA_T 500

#define GAME_OF_LIFE_CONSTANTS_H
#endif